/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated.alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated.digital-twin'
import { Route as AuthenticatedEngineRouteImport } from './routes/_authenticated.engine'
import { Route as AuthenticatedFieldReportingRouteImport } from './routes/_authenticated.field-reporting'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated.logistics'
import { Route as AuthenticatedRiskPredictionRouteImport } from './routes/_authenticated.risk-prediction'
import { Route as AuthenticatedRouteOptimizerRouteImport } from './routes/_authenticated.route-optimizer'
import { Route as AuthenticatedWhatIfRouteImport } from './routes/_authenticated.what-if'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngineRoute = AuthenticatedEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFieldReportingRoute =
  AuthenticatedFieldReportingRouteImport.update({
    id: '/field-reporting',
    path: '/field-reporting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskPredictionRoute =
  AuthenticatedRiskPredictionRouteImport.update({
    id: '/risk-prediction',
    path: '/risk-prediction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRouteOptimizerRoute =
  AuthenticatedRouteOptimizerRouteImport.update({
    id: '/route-optimizer',
    path: '/route-optimizer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWhatIfRoute = AuthenticatedWhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/field-reporting': typeof AuthenticatedFieldReportingRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/risk-prediction': typeof AuthenticatedRiskPredictionRoute
  '/route-optimizer': typeof AuthenticatedRouteOptimizerRoute
  '/what-if': typeof AuthenticatedWhatIfRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/field-reporting': typeof AuthenticatedFieldReportingRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/risk-prediction': typeof AuthenticatedRiskPredictionRoute
  '/route-optimizer': typeof AuthenticatedRouteOptimizerRoute
  '/what-if': typeof AuthenticatedWhatIfRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/engine': typeof AuthenticatedEngineRoute
  '/_authenticated/field-reporting': typeof AuthenticatedFieldReportingRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/risk-prediction': typeof AuthenticatedRiskPredictionRoute
  '/_authenticated/route-optimizer': typeof AuthenticatedRouteOptimizerRoute
  '/_authenticated/what-if': typeof AuthenticatedWhatIfRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/digital-twin'
    | '/engine'
    | '/field-reporting'
    | '/logistics'
    | '/risk-prediction'
    | '/route-optimizer'
    | '/what-if'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/digital-twin'
    | '/engine'
    | '/field-reporting'
    | '/logistics'
    | '/risk-prediction'
    | '/route-optimizer'
    | '/what-if'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/digital-twin'
    | '/_authenticated/engine'
    | '/_authenticated/field-reporting'
    | '/_authenticated/logistics'
    | '/_authenticated/risk-prediction'
    | '/_authenticated/route-optimizer'
    | '/_authenticated/what-if'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engine': {
      id: '/_authenticated/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof AuthenticatedEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/field-reporting': {
      id: '/_authenticated/field-reporting'
      path: '/field-reporting'
      fullPath: '/field-reporting'
      preLoaderRoute: typeof AuthenticatedFieldReportingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk-prediction': {
      id: '/_authenticated/risk-prediction'
      path: '/risk-prediction'
      fullPath: '/risk-prediction'
      preLoaderRoute: typeof AuthenticatedRiskPredictionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/route-optimizer': {
      id: '/_authenticated/route-optimizer'
      path: '/route-optimizer'
      fullPath: '/route-optimizer'
      preLoaderRoute: typeof AuthenticatedRouteOptimizerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/what-if': {
      id: '/_authenticated/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof AuthenticatedWhatIfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedEngineRoute: typeof AuthenticatedEngineRoute
  AuthenticatedFieldReportingRoute: typeof AuthenticatedFieldReportingRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedRiskPredictionRoute: typeof AuthenticatedRiskPredictionRoute
  AuthenticatedRouteOptimizerRoute: typeof AuthenticatedRouteOptimizerRoute
  AuthenticatedWhatIfRoute: typeof AuthenticatedWhatIfRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedEngineRoute: AuthenticatedEngineRoute,
  AuthenticatedFieldReportingRoute: AuthenticatedFieldReportingRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedRiskPredictionRoute: AuthenticatedRiskPredictionRoute,
  AuthenticatedRouteOptimizerRoute: AuthenticatedRouteOptimizerRoute,
  AuthenticatedWhatIfRoute: AuthenticatedWhatIfRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
